server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sports_center}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:f27dacd186810e78c0fd8ba65ecf3f1524ff087c5e86773d5172d424b3fd201f}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:*}
